// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxXWsRYoyxbyogodRrCtFAgiH37TmmOfY',
    appId: '1:152617371113:web:eb49fbadfdf26a3c7db778',
    messagingSenderId: '152617371113',
    projectId: 'athar-stg',
    authDomain: 'athar-stg.firebaseapp.com',
    storageBucket: 'athar-stg.firebasestorage.app',
    measurementId: 'G-Q5SM70CM0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9d-Uwy1dTW-W6A5c3YEoFZxmelFuHiAU',
    appId: '1:152617371113:android:76965efc1d0a92ae7db778',
    messagingSenderId: '152617371113',
    projectId: 'athar-stg',
    storageBucket: 'athar-stg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0UtLI_4ctC8waC9PrgkUr7-vbj9q3YcA',
    appId: '1:152617371113:ios:e0c5c61e27d69c027db778',
    messagingSenderId: '152617371113',
    projectId: 'athar-stg',
    storageBucket: 'athar-stg.firebasestorage.app',
    iosBundleId: 'com.example.verygoodcore.athar.stg',
  );
}
