include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    flutter_style_todos: false
    one_member_abstracts: false
    public_member_api_docs: false
    sort_constructors_first: false
    require_trailing_commas: false
    lines_longer_than_80_chars: false

analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
    avoid_setters_without_getters: ignore
  exclude:
    - "**.g.dart"
    - "**/generated_plugin_registrant.dart"
