name: athar
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.4.0
  cloud_firestore: ^5.3.0
  dartx: ^1.2.0
  duration_picker: ^1.2.0
  equatable: ^2.0.5
  firebase_auth: ^5.3.0
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  form_inputs:
    git: https://github.com/ISL270/form_inputs
  formz: ^0.8.0
  fpdart: ^1.1.0
  gap: ^3.0.1
  get_it: ^8.0.0
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hydrated_bloc: ^9.1.5
  injectable: ^2.4.4
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  modal_progress_hud_nsn: ^0.5.1
  numberpicker: ^2.1.2
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  super_cupertino_navigation_bar: ^2.1.2
  theme_tailor_annotation: ^3.0.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.6.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  theme_tailor: ^3.0.1
  very_good_analysis: ^6.0.0

dependency_overrides:
  analyzer: ^6.3.0


flutter_gen:
  output: lib/app/core/assets_gen/
  line_length: 100


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
