// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN-lcLpMkZwZtxXsJnEwITlKACWGMzYyI',
    appId: '1:896641288556:web:a8bd56594075125b748b49',
    messagingSenderId: '896641288556',
    projectId: 'athar-dev',
    authDomain: 'athar-dev.firebaseapp.com',
    storageBucket: 'athar-dev.firebasestorage.app',
    measurementId: 'G-077Z81YR37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnY2g_rBVjdLphp_c2rPeDhY6o3rgiHxQ',
    appId: '1:896641288556:android:8e4035bf7788e27b748b49',
    messagingSenderId: '896641288556',
    projectId: 'athar-dev',
    storageBucket: 'athar-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_JVdbWsKI_64z1Ey4RnCvJ2VuvQtLYuo',
    appId: '1:896641288556:ios:bb1fa8a76fc33535748b49',
    messagingSenderId: '896641288556',
    projectId: 'athar-dev',
    storageBucket: 'athar-dev.firebasestorage.app',
    iosBundleId: 'com.example.verygoodcore.athar.dev',
  );
}
